---
# ansible-playbook main.yml
- name: Run echoip on remote server
  hosts: host2
  sudo: True
  tasks:
    - name: Start echoip container
      command: docker run -d --net=host --restart=always --name=echoip grahamking/echoip
